# Data Input and Output

In [1]:
pwd

'C:\\Users\\ativarovsky.ALTAMEDORG\\Documents\\python-ml-course\\Pandas'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('example')

In [4]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [5]:
df.to_csv('My_output') # note that this saves an index (Unnamed below), use index = False if you don't want this

In [6]:
pd.read_csv('My_output')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [7]:
df.to_excel('Excel_Sample2.xlsx', sheet_name = 'NewSheet')

### Reading html files (web scraping)

In [8]:
data = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [10]:
type(data) # note this is a list of several tables

list

In [11]:
data

[                                          Bank Name               City  \
 0                       Tioga-Franklin Savings Bank       Philadelphia
 1                               Small Business Bank             Lenexa
 2     Kentland Federal Savings and Loan Association           Kentland
 3           Community Bank and Trust - West Georgia           LaGrange
 4                 Metropolitan Capital Bank & Trust            Chicago
 5                      The Santa Anna National Bank         Santa Anna
 6                              Pulaski Savings Bank            Chicago
 7                The First National Bank of Lindsay            Lindsay
 8             Republic First Bank dba Republic Bank       Philadelphia
 9                                     Citizens Bank           Sac City
 10                         Heartland Tri-State Bank            Elkhart
 11                              First Republic Bank      San Francisco
 12                                   Signature Bank           New York
 13                              Silicon Valley Bank        Santa Clara
 14                                Almena State Bank             Almena
 15                       First City Bank of Florida  Fort Walton Beach
 16                             The First State Bank      Barboursville
 17                               Ericson State Bank            Ericson
 18                 City National Bank of New Jersey             Newark
 19                                    Resolute Bank             Maumee
 20                            Louisa Community Bank             Louisa
 21                             The Enloe State Bank             Cooper
 22              Washington Federal Bank for Savings            Chicago
 23  The Farmers and Merchants State Bank of Argonia            Argonia
 24                              Fayette County Bank         Saint Elmo

             State   Cert                              Acquiring Institution  \
 0    Pennsylvania  33802  Second Federal Savings and Loan Association of...
 1          Kansas  25744           The Farmers State Bank of Oakley, Kansas
 2         Indiana  28722                                      Kentland Bank
 3         Georgia  25796                                        Anchor Bank
 4        Illinois  57488                            First Independence Bank
 5           Texas   5520                          Coleman County State Bank
 6        Illinois  28611                                    Millennium Bank
 7        Oklahoma   4134                             First Bank & Trust Co.
 8    Pennsylvania  27332                  Fulton Bank, National Association
 9            Iowa   8758                          Iowa Trust & Savings Bank
 10         Kansas  25851                             Dream First Bank, N.A.
 11     California  59017                          JPMorgan Chase Bank, N.A.
 12       New York  57053                                Flagstar Bank, N.A.
 13     California  24735                First–Citizens Bank & Trust Company
 14         Kansas  15426                                        Equity Bank
 15        Florida  16748                          United Fidelity Bank, fsb
 16  West Virginia  14361                                     MVB Bank, Inc.
 17       Nebraska  18265                         Farmers and Merchants Bank
 18     New Jersey  21111                                    Industrial Bank
 19           Ohio  58317                                 Buckeye State Bank
 20       Kentucky  58112                  Kentucky Farmers Bank Corporation
 21          Texas  10716                                 Legend Bank, N. A.
 22       Illinois  30570                                 Royal Savings Bank
 23         Kansas  17719                                        Conway Bank
 24       Illinois   1802                          United Fidelity Bank, fsb

          Closing Date  Fund  Sort ascending
 0     August 21, 2026                 10554
 1       July 17, 2026                 10553
 2       July 10, 2026                 10552
 3         May 1, 2026                 10551
 4    January 30, 2026                 10550
 5       June 27, 2025                 10549
 6    January 17, 2025                 10548
 7    October 18, 2024                 10547
 8      April 26, 2024                 10546
 9    November 3, 2023                 10545
 10      July 28, 2023                 10544
 11        May 1, 2023                 10543
 12     March 12, 2023                 10540
 13     March 10, 2023                 10539
 14   October 23, 2020                 10538
 15   October 16, 2020                 10537
 16      April 3, 2020                 10536
 17  February 14, 2020                 10535
 18   November 1, 2019                 10534
 19   October 25, 2019                 10533
 20   October 25, 2019                 10532
 21       May 31, 2019                 10531
 22  December 15, 2017                 10530
 23   October 13, 2017                 10529
 24       May 26, 2017                 10528  ]

In [13]:
data[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528

### Working with SQL

In [15]:
import pyodbc

In [22]:
#from sqlalchemy import create_engine

In [26]:
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=DB-PROD-REPORT;"
    "DATABASE=ALTAMED_DATASCIENCE;"
    "Trusted_Connection=yes;"  # Or UID=user;PWD=password
    "TrustServerCertificate=yes;"
)

In [27]:
query = "SELECT TOP 100* FROM dbo.VG_ER_Visits"

In [28]:
df = pd.read_sql_query(query, conn)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [29]:
df.head()

,ER_Claim_Number,ER_Visit_Date,ER_DiagCode,ER_Loc_Name,Source_System,PatientEpicID,PrimaryMRN,LANES_admit_reason,ER_CCSR_Category_1,ER_Classification,...,Viva_Gold_Eff_Dt,Viva_Gold_Term_Dt,AVP_Region,Assigned_Clinic,Assigned_PCP,FQHC_vs_IPA,days_Enrolled,Weeks_Enrolled,Months_Enrolled,er_follow_up_date
0,NA,2026-09-17,NA,Cedars-Sinai Medical Center,LANES,Z521602,20108735,None,None,ER - Unclassified,...,2022-07-01,2099-12-31,Region 6 - AltaMed Viva Gold,Viva Gold - Commerce,"PUERTAS, RICARDO",FQHC,1543,220,55.0,2022-08-29
1,NA,2026-09-17,NA,Queen of the Valley Hospital,LANES,Z665145,20252273,None,None,ER - Unclassified,...,2025-11-01,2099-12-31,Region 6 - AltaMed Viva Gold,Viva Gold - West Covina Amar,"CHIRIBOGA HURTADO, JUAN JAVIER",FQHC,324,46,11.0,2022-08-29
2,NA,2026-09-16,NA,Queen of the Valley Hospital,LANES,Z665145,20252273,None,None,ER - Unclassified,...,2025-11-01,2099-12-31,Region 6 - AltaMed Viva Gold,Viva Gold - West Covina Amar,"CHIRIBOGA HURTADO, JUAN JAVIER",FQHC,324,46,11.0,2022-08-29
3,NA,2026-09-16,NA,Queen of the Valley Hospital,LANES,Z348616,311188,None,None,ER - Unclassified,...,2025-10-01,2099-12-31,Region 6 - AltaMed Viva Gold,Viva Gold - West Covina Amar,"CHIRIBOGA HURTADO, JUAN JAVIER",FQHC,355,50,12.0,2022-08-29
4,NA,2026-09-14,NA,Queen of the Valley Hospital,LANES,Z54641,838672,None,None,ER - Unclassified,...,2025-11-01,2099-12-31,Region 6 - AltaMed Viva Gold,Viva Gold - West Covina Amar,"CHIRIBOGA HURTADO, JUAN JAVIER",FQHC,324,46,11.0,2022-08-29