# Operations

In [2]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame({'col1': [1,2,3,4], 
                   'col2': [444,555,666,444], 
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

How many unique values in column 2?

In [8]:
df['col2']

0    444
1    555
2    666
3    444
Name: col2, dtype: int64

In [10]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [13]:
df['col2'].nunique()

3

Value counts

In [16]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

## Select Data (using conditional selection)

In [20]:
df['col1']>1 # just a boolean

0    False
1     True
2     True
3     True
Name: col1, dtype: bool

In [23]:
df[df['col1']>1]

   col1  col2 col3
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Apply Method

In [25]:
def times2(x) : 
    return(x*2)

In [27]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

Or for shorthand, use lambda function

In [28]:
df['col1'].apply(lambda x: x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [29]:
# how to choose columns and index
df.columns # note that this is an attribute, not a function, so doesn't need parentheses

Index(['col1', 'col2', 'col3'], dtype='object')

In [30]:
df.index # note that this is also an attribute

RangeIndex(start=0, stop=4, step=1)

### Sorting

In [33]:
df.sort_values(by = 'col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

### Null Values

In [36]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

### Pivot Tables

In [37]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [38]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [39]:
df.pivot_table(values = 'D', index = ['A', 'B'], columns = ['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN